/**
 * Shared Types - Generated by CIRCULAR_BREAKER Agent
 * 
 * This file contains interfaces and types extracted from circular dependencies
 * to break import cycles and improve architectural health.
 */

// TODO: Move actual type definitions here from the original files
export interface Seven {
  // TODO: Move definition from original file
}

export interface SevenControl {
  // TODO: Move definition from original file
}

export interface SevenInteractiveShell {
  // TODO: Move definition from original file
}

// Re-export commonly used types
export type { Seven, SevenControl, SevenInteractiveShell };
