name: seven-companion-ci
on: 
  push:
    branches: [ main, fix/*, feature/* ]
  pull_request:
    branches: [ main ]

jobs:
  ci:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    
    services:
      # SQLite is file-based, no service needed
      
    steps:
      - name: Checkout Seven Companion App
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with: 
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: seven-companion-app/package-lock.json
          
      - name: Install Dependencies
        working-directory: seven-companion-app
        run: npm ci
        
      - name: TypeScript Compilation Check
        working-directory: seven-companion-app
        run: |
          npx tsc --noEmit
          echo "✅ TypeScript compilation successful"
          
      - name: Database Migration Test
        working-directory: seven-companion-app
        run: |
          # Create test database directory
          mkdir -p data
          # Test database adapter selection
          SEVEN_DEV_BYPASS_AUTH=1 npx tsx src/db/index.ts
          echo "✅ Database adapter selection working"
          
      - name: Authentication System Test
        working-directory: seven-companion-app
        env:
          SEVEN_DEV_BYPASS_AUTH: "1"
        run: |
          # Test Quadran-Lock authentication
          npx tsx src/auth/creator_proof.ts
          echo "✅ Authentication system operational"
          
      - name: Mobile Memory Client Test
        working-directory: seven-companion-app
        run: |
          # Test cross-platform memory client
          npx tsx test-mobile-memory.ts
          echo "✅ Mobile memory integration working"
          
      - name: Start Test Server
        working-directory: seven-companion-app
        env:
          SEVEN_DEV_BYPASS_AUTH: "1"
          NODE_ENV: "test"
        run: |
          # Start server in background for health checks
          timeout 30s npx tsx test-metrics-server.ts &
          sleep 3
          echo "✅ Test server started"
          
      - name: Health Endpoint Check
        working-directory: seven-companion-app
        run: |
          # Test health endpoint
          response=$(curl -sf http://localhost:8787/health || echo "failed")
          if [[ "$response" == "failed" ]]; then
            echo "❌ Health check failed"
            exit 1
          fi
          echo "✅ Health endpoint responding"
          
      - name: Metrics Endpoint Check
        working-directory: seven-companion-app
        run: |
          # Test metrics endpoint
          response=$(curl -sf http://localhost:8787/metrics || echo "failed")
          if [[ "$response" == "failed" ]]; then
            echo "❌ Metrics check failed"
            exit 1
          fi
          echo "✅ Metrics endpoint responding"
          
      - name: tRPC Client Validation
        working-directory: seven-companion-app
        run: |
          # Validate tRPC client structure
          npx tsx -e "
            import { trpc } from './src/api/trpc.js';
            console.log('✅ tRPC client imported successfully');
          "
          
      - name: Authentication Bypass Test
        working-directory: seven-companion-app
        env:
          SEVEN_DEV_BYPASS_AUTH: "1"
        run: |
          # Test auth bypass functionality
          npx tsx -e "
            import { enforceQuadran } from './src/auth/security_middleware.js';
            const result = await enforceQuadran({}, {});
            if (!result.ok) throw new Error('Auth bypass failed');
            console.log('✅ Development auth bypass working');
          "
          
      - name: Text Normalization Test
        working-directory: seven-companion-app
        run: |
          # Test text normalization robustness
          npx tsx -e "
            import { normalizeText, detectBypassAttempt } from './src/auth/text-normalizer.js';
            const normalized = normalizeText('Test 🚀 Input');
            if (detectBypassAttempt('<script>')) console.log('✅ Bypass detection working');
            console.log('✅ Text normalization operational');
          "
          
      - name: Seven Core Integration Check
        working-directory: seven-companion-app
        env:
          SEVEN_DEV_BYPASS_AUTH: "1"
        run: |
          # Test Seven consciousness core integration
          npx tsx -e "
            import { SevenConsciousnessCore } from './src/backend/seven-consciousness-core.js';
            console.log('✅ Seven consciousness core integration ready');
          " || echo "⚠️ Core integration needs attention (non-blocking)"
          
      - name: Claude Agent Manifests Check
        working-directory: seven-companion-app
        run: |
          # Verify Claude agent manifests are generated
          if [ -d ".claude/agents/generated" ]; then
            count=$(ls .claude/agents/generated/*.yaml 2>/dev/null | wc -l)
            echo "✅ Found $count Claude agent manifests"
          else
            echo "⚠️ No Claude agent manifests found"
          fi
          
      - name: Security Validation
        working-directory: seven-companion-app
        run: |
          # Basic security checks
          echo "🔒 Running security validation..."
          
          # Check for hardcoded secrets (basic patterns)
          if grep -r "password.*=" src/ --include="*.ts" | grep -v "Password" | head -1; then
            echo "❌ Potential hardcoded credentials found"
            exit 1
          fi
          
          # Check authentication is enforced
          if ! grep -r "Quadran-Lock" src/ --include="*.ts" >/dev/null; then
            echo "❌ Authentication enforcement not found"
            exit 1
          fi
          
          echo "✅ Basic security validation passed"
          
      - name: CI Summary
        working-directory: seven-companion-app
        run: |
          echo "🎯 ============================="
          echo "🤖 SEVEN COMPANION CI COMPLETE"
          echo "🎯 ============================="
          echo "✅ TypeScript compilation"
          echo "✅ Database adapter selection"
          echo "✅ Authentication system"
          echo "✅ Mobile memory client"
          echo "✅ Health/metrics endpoints"
          echo "✅ tRPC client validation"
          echo "✅ Text normalization robustness"
          echo "✅ Security validation"
          echo "🎯 All systems operational"